### ISSUE TITLE
Vision Demo detecting pose errors with Domain=com.apple.vis Code=9

### ISSUE THREAD

**Issue by TJ-C** [ktustanowski/visiondemo#8]
```
do {
        try requestHandler.perform([bodyPoseRequest])
    } catch {
        print("Can't make the request due to \(error)")
```

Can't make the request due to Error Domain=com.apple.vis Code=9 "Unable to setup request in VNDetectHumanBodyPoseRequest" UserInfo={NSLocalizedDescription=Unable to setup request in VNDetectHumanBodyPoseRequest}

Xcode Version 13.0 (13A233)

Just tested it on a real device and there's no error. So it looks like pose detection can't be run in a simulator or playground.

**Comment by ktustanowski** [comment]
Oh man, I think I must have missed the notifications. Sorry for the enormous delay.

Yes - I also encountered requests that just don't work in the playground or the simulator. I didn't investigate why this happens yet - I just see that some of the requests are not working properly on the sim or playground.
